// Preserve the saved proof document and its normal-speed playback contract.
export function htmlProof(files, fps, width, height, disabled, labels = null) {
  const payload =
      JSON.stringify({files, fps, width, height, disabled, labels}).replaceAll('<', '\\u003c');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ambiance motion proof</title>
<style>body{background:#14151b;color:#eee;font:16px system-ui;margin:24px}main{display:flex;gap:16px;flex-wrap:wrap}figure{margin:0}canvas{display:block;max-width:100%;height:auto;background:#000;width:${
      width}px}figcaption{margin:8px 0}button,select,input{font:inherit;margin:6px}p{max-width:70ch}</style>
<h1>Motion proof</h1><p>Normal-speed raster frames from the shared scene engine. This short segment repeats for inspection; its end may be an arbitrary cut within the full scene loop. Selected layers are hidden in the comparison, revealing the existing backing.</p>
<button id="play" disabled>Pause</button><label>Speed <select id="speed"><option value="1">1× (actual speed)</option><option value=".5">0.5×</option></select></label><input aria-label="Frame" id="seek" type="range" min="0" value="0"><span id="status">Loading frames…</span><main id="panes"></main>
<script>const config=${
      payload};const panes=document.querySelector('#panes'),status=document.querySelector('#status'),seek=document.querySelector('#seek'),play=document.querySelector('#play');let playing=true,current=0,base=0,last=performance.now();const views=config.files.map((list,i)=>{const f=document.createElement('figure'),label=document.createElement('figcaption'),c=document.createElement('canvas');c.width=config.width;c.height=config.height;label.textContent=config.labels?.[i]??(i?'Disabled: '+config.disabled.join(', '):'Current scene');f.append(label,c);panes.append(f);return {ctx:c.getContext('2d'),images:list.map(src=>{const image=new Image();image.src=src;return image;})};});seek.max=config.files[0].length-1;function draw(n){for(const v of views)v.ctx.drawImage(v.images[n],0,0);seek.value=n;status.textContent=(n/config.fps).toFixed(2)+' s · frame '+n;}Promise.all(views.flatMap(v=>v.images.map(i=>i.decode()))).then(()=>{play.disabled=false;last=performance.now();draw(0);function tick(now){if(playing){base+=Math.max(0,now-last)/1000*Number(document.querySelector('#speed').value);current=Math.floor(base*config.fps)%config.files[0].length;draw(current);}last=now;requestAnimationFrame(tick);}requestAnimationFrame(tick);}).catch(e=>{status.textContent='Could not load proof frames: '+e.message;});play.onclick=()=>{playing=!playing;play.textContent=playing?'Pause':'Play';};seek.oninput=()=>{playing=false;play.textContent='Play';current=Number(seek.value);base=current/config.fps;draw(current);};</script></html>`;
}
